# Generated by Django 4.2.13 on 2024-12-24 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Earner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('points', models.IntegerField()),
                ('createdOnDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedOnDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('iconType', models.CharField(max_length=20)),
                ('points', models.IntegerField()),
                ('createdOnDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedOnDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('iconType', models.CharField(max_length=20)),
                ('points', models.IntegerField()),
                ('completed', models.BooleanField(default=False)),
                ('completeByDate', models.DateField(blank=True)),
                ('createdOnDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedOnDate', models.DateTimeField(auto_now=True)),
                ('earner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='earnit.earner')),
            ],
        ),
    ]
