# Generated by Django 4.2.13 on 2024-07-09 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earnit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward', models.CharField(max_length=200)),
                ('iconType', models.CharField(max_length=20)),
                ('points', models.IntegerField()),
                ('createdOnDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedOnDate', models.DateTimeField(auto_now=True)),
                ('earner', models.ManyToManyField(to='earnit.earner')),
            ],
        ),
    ]
